# Site settings
title: Jae Yong Kim 
header-img: img/home-bg.png
email: kim900180@gmail.com
copyright_name: kim900180
description: > # this means to ignore newlines until "baseurl:"
  Coding Blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kim900180
learn_profile: kim900180
email_username: kim900180@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
